# Домашнее задание. Линейная алгебра и библиотека NumPy
В этом домашнем задании вам предстоит самостоятельно реализовать линейно-алгебраические операции с помощью чистого Python, а затем попрактиковаться в использовании уже готовых реализаций из numpy. Кроме того, вы сравните время работы вашей реализации с реализацией из библиотеки NumPy и убедитесь, что скорость работы "коробочных" реализаций выше.

In [1]:
import numpy as np
import random
import scipy.stats as sps

## Задание 1
Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [2]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.56039333 0.85014397 0.67299879] [0.84880294 0.2486955  0.00120547]


In [3]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """
    result = 0 
    for elem_a, elem_b in zip(a,b):
      result += elem_a*elem_b


    return result

In [4]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return a @ b

In [5]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 44.3 µs
CPU times: user 122 µs, sys: 0 ns, total: 122 µs
Wall time: 266 µs


первую функцию можно записать короче

In [ ]:
import numpy as np

def no_numpy_scalar(v1, v2):
    #param v1, v2: lists of 3 ints
    #YOUR CODE: please do not use numpy

    result = sum([x*y for x,y in zip(v1,v2)]) 
    return result

def numpy_scalar (v1, v2):
    #param v1, v2: np.arrays[3]
    #YOUR CODE

    result = v1 @ v2
    return result

## Задание 2
Вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета `numpy` и с ним.

In [24]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.78709037 0.18095205 0.79456718 ... 0.02024787 0.07058279 0.61065367]
 [0.44155693 0.75901836 0.41909733 ... 0.90831727 0.66170333 0.27255696]
 [0.70364662 0.09860743 0.52384336 ... 0.54326285 0.52393037 0.27584936]
 ...
 [0.04592494 0.6733872  0.11535892 ... 0.50195221 0.55526378 0.90368276]
 [0.04224572 0.58590602 0.84590377 ... 0.56266781 0.03771148 0.55489097]
 [0.47391871 0.27646178 0.6167138  ... 0.70087705 0.70903451 0.33528185]]
[[0.25902281 0.63118699 0.67316305 ... 0.87804915 0.92438947 0.77068109]
 [0.15817314 0.38992333 0.95223028 ... 0.14143723 0.05908903 0.80698201]
 [0.71311721 0.28573491 0.95338781 ... 0.21354748 0.74825792 0.78778404]
 ...
 [0.56419123 0.7574567  0.5188097  ... 0.72744554 0.3822005  0.57878215]
 [0.50326475 0.11637867 0.03986345 ... 0.83597498 0.12956111 0.87964234]
 [0.06193721 0.0263053  0.32977178 ... 0.17800584 0.85633973 0.09004359]]


In [25]:
print(a.ndim)
print(b.ndim)

2
2


In [26]:
print(a.shape)
print(b.shape)

(100, 100)
(100, 100)


In [27]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    result = []
    size = a.shape[0]
    for i in range(size):
      for j in range(size):
        #print(a[i])
        #print(b[:,j])
        sum = []
        sum = [x*y for x,y in zip(a[i], b[:,j])]
        #print(type(sum))
        #print(sum)
        result_sum = 0
        for el in sum:
        #print(el)
          result_sum += el
        result.append(result_sum)
    return np.array(result).reshape(size,size)
    

In [28]:
def np_mult(a, b):
    """  
    a: np.array[size, size]              --- первая матрица-аргумент
    b: np.array[size, size]              --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a@b

In [29]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 313 ms, sys: 0 ns, total: 313 ms
Wall time: 315 ms


In [30]:
M1.shape

(100, 100)

In [ ]:
list(M1)

In [ ]:
M1[:5,:5]

In [ ]:
M2[:5,:5]

In [34]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 544 µs, sys: 3.03 ms, total: 3.58 ms
Wall time: 10.8 ms


In [36]:
M2.shape

(100, 100)

In [37]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций numpy, а другая --- с помощью numpy. На вход первой задаче подаются списки размера size по size элементов в каждом. На вход второй задаче подаются объекты типа np.ndarray --- квадратные матрицы одинакового размера. 

Первая функция должна возвращать список списков, а вторая -- np.array.

In [ ]:
import numpy as np

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param second: list of "size" lists, each contains "size" floats
    """
    second_T = []
    for i in range(len(second)):
        array_str = []
        for j in range(len(second)):
            array_str.append(second[j][i])
        second_T.append(array_str)    
    

    #YOUR CODE: please do not use numpy
    result = []
    size = len(first)
    for i in range(size):
        result_str = []
        for j in range(size):
        #print(a[i])
        #print(b[:,j])
            sum = 0
            sum = [x*y for x,y in zip(first[i], second_T[j])]
            #print(type(sum))
            #print(sum)
            result_sum = 0
            for el in sum:
                #print(el)
                result_sum += el
            result_str.append(result_sum)
        result.append(result_str) #YOUR CODE: create list of lists, not np.array
    return result

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """

    #YOUR CODE: please use numpy

    result = first@second #YOUR CODE: create np.array
    return result

более изящное решение

In [38]:
import numpy as np

def no_numpy_mult(a, b):
    return [[sum(a[i][k]*b[k][j] for k in range(len(a))) for j in range(len(a))] for i in range(len(a))]

def numpy_mult(first, second):
    return first @ second

## Задание 3
Постановка задачи линейной регрессии, о которой мы будем говорить в следующих модулях, выглядит так.

**Дано**: матрица $X$ размера $\ell \times n$ и вектор $y$ размерности $\ell$. 

**Необходимо**: подобрать вектор $w$ размерности $n$, для которого выражение $||Xw - y||^2_2$ будет минимально возможным, где $||a||_2^2$ --- квадрат нормы вектора $a$, то есть сумма квадратов компонент вектора $a$.

Даны матрица $X$ и векторы $w$, $y$. Напишите функцию, которая находит значение выражения $||Xw - y||^2_2$. Используйте библиотеку `numpy` и ее встроенные функции. Предлагаем вам загуглить, как вычислять норму вектора с помощью `numpy`. **Следите за правильными размерностями при применении линейно-алгебраических операций!**

In [40]:
def calculate_loss_function(X, w, y):
    #YOUR CODE
    b = X.dot(w) - y

    return np.sum(b**2) #YOUR CODE

In [43]:
# test
X = np.array([1,2,3,4,5,6]).reshape(3, 2)
w = np.array([0.5, -1.2])
y = np.array([2, -1, 0])

assert np.allclose(calculate_loss_function(X, w, y), 42.58999999999999)

In [42]:
calculate_loss_function(X,w,y)

42.58999999999999

## Задание 4
В случае, если ранг матрицы $X$ превосходит $n$, минимальное значение выражения $||Xw - y||^2_2$ при данных $X$ и $y$ достигается на векторе $$w^{*} = (X^{\top}X)^{-1}X^{\top}y.$$ 

Даны матрица $X$ размера $\ell \times n$ и вектор $y$ размера $\ell$. Вычислите значение выражения $W^{*}$ по формуле, указанной выше. Используйте встроенные матричные операции в `numpy`: матричное произведение, транспонирование, вычисление обратной матрицы. Верните на выход одномерный np.array. **Следите за правильными размерностями при применении линейно-алгебраических операций!**

In [44]:
def solve_linear_regression(X, y):
    #YOUR_CODE
    w_opt = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y) #YOUR CODE
    
    return w_opt

In [45]:
#test
X = np.array([1,2,3,4,5,6]).reshape(3, 2)
y = np.array([2, -1, 0])

assert np.allclose(solve_linear_regression(X, y), np.array([-2.33333333,  1.83333333]))
